services:
    prometheus:
        image: prom/prometheus:latest
        container_name: srv_prometheus
        restart: unless-stopped
        ports: 
            - "9090:9090"
        volumes:
            - ./prometheus/db:/prometheus
            - ./prometheus/etc:/etc/prometheus
        networks:
            - prografnet

    grafana:
        image: grafana/grafana-oss:latest
        container_name: srv_grafana
        restart: unless-stopped
        ports: 
            - "3000:3000"
        volumes:
            - ./grafana/storage:/var/lib/grafana
            - ./grafana/etc:/etc/grafana
        networks:
            - prografnet
            
    bindexporter:
        image: prometheuscommunity/bind-exporter:latest
        container_name: srv_bindexporter
        restart: unless-stopped
        environment:
            - "--bind.stats-url=http://10.10.10.1:8053 --web.listen-address=:9121 --bind.stats-groups=server,view,tasks" 
        networks:
            - prografnet

networks:
    prografnet:
        ipam:
            driver: default
            config:
                - subnet: 172.21.0.0/24
